const salarioHora: number          = 12.50;
const numeroEmpleado: number       = 42;
const evaluacionDesempeno: number   = 4.5;
const hexColorBadge: number        = 0x00A86B;  
const emailEmpleado: string        = "empleado@empresa.com";
const tipoContrato: string         = 'Contrato Indefinido';
const empleadosApi: string         = `/api/v1/empleados`;
const empleadoActivo: boolean      = true;
const requiereCapacitacion: boolean = false;
const esRemoto: boolean            = false;
const horasTotales                 = 160;
const horasExtraPrimitivo          = 20;
const horasBase                    = horasTotales - horasExtraPrimitivo;  
const empleadoEmail                = "  juan.perez@empresa.com  ";
console.log(empleadoEmail.trim().toLowerCase()); 
console.log(emailEmpleado.includes("empresa"));    
console.log(emailEmpleado.split("@"));              
console.log(emailEmpleado.split("@")[1]); 
let registro: string = "Emp42;Ventas;160;08-10-2023";
console.log(registro.split(";")[0]);         
const puedePromocionar: boolean = empleadoActivo && !requiereCapacitacion;
console.log(puedePromocionar); 
