const horasCapacitacion: number[] = [5, 12, 18, 25, 30];
const departamentosArray: Array<string> = ["Norte", "Centro", "Sur"];   
const empleadosPorDepto = [10, 20, 30]; 
console.log(`Horas de capacitación: ${horasCapacitacion}`);
console.log(`Departamentos: ${departamentosArray}`);
console.log(`Empleados: ${empleadosPorDepto}`);
const horasExtraArray: number[] = horasCapacitacion.map((t) => t + 5);       
const capacitacionesCortas: number[] = horasCapacitacion.filter((t) => t <= 15); 
const totalEmpleadosDepto: number = empleadosPorDepto.reduce((acc, p) => acc + p, 0); 
console.log(`Horas extra: ${horasExtraArray}`);
console.log(`Capacitaciones cortas: ${capacitacionesCortas}`);
console.log(`Total Empleados: ${totalEmpleadosDepto}`);
horasCapacitacion.push(40);       
horasCapacitacion.unshift(1);    
const ultimaHora = horasCapacitacion.pop();   
const primeraHora = horasCapacitacion.shift(); 
console.log(`Después de mutaciones: ${horasCapacitacion}`);
console.log(`Primera: ${primeraHora}, Última: ${ultimaHora}`);
const hayDeptoCentro: boolean = departamentosArray.includes("Centro"); 
console.log(`Existe departamento Centro: ${hayDeptoCentro}`);
const indiceSur: number = departamentosArray.indexOf("Sur");      
console.log(`Índice de departamento Sur: ${indiceSur}`);
const capacitacionLarga: number | undefined = horasCapacitacion.find((t) => t > 20); 
console.log(`Capacitación larga encontrada: ${capacitacionLarga}`); 
